### ISSUE TITLE
Links im Teaser Element werden nicht richtig ersetzt.

### ISSUE THREAD

**Issue by Raul1975** [oveleon/contao-glossary-bundle#13]
Hallo,

wenn die in einem Glossar Eintrag im Teaser Text einen Link auf einen andere Seite der Website einfüge, wird dieser leider nicht korrekt ersetzt. Diese führt dann zu einem 404.

Beispiel:

Seite: https://www.leberkrebshilfe.info/kurative-verfahren.html

Begriff: Resektion

Verlinkung im Teaser auf "Hier finden Sie ausführliche Informationen in der entsprechenden Rubrik."
mit Link zu: {{link_url::130|urlattr}}

wird dann beim Hover im Frontend zu: https://www.leberkrebshilfe.info/%7B%7Blink_url::130%7Curlattr%7D%7D

Klick auf den Link/Begriff "Resektion" führt dieser zu "https://www.leberkrebshilfe.info/exikon/resektion.html" 
Was korrekt ist.

Klicke ich hier auf "Hier finden Sie ausführliche Informationen in der entsprechenden Rubrik."
Komme ich zu "https://www.leberkrebshilfe.info/resektion.html"
Was korrekt ist.

Ergo. Die Links im Teaser werden nicht richtig ersetzt.

**Comment by zoglo** [comment]
Hallo Raul,

es sieht aus, als wenn die Insert-Tags nicht über die API aufgelöst werden können. Ich habe gerade einen Fix in der dev-develop eingespielt. Könntest du es die Version einmal testen?

**Comment by Raul1975** [comment]
Hallo,

ich habe den "dev-develop" gerade getestet. Funktioniert. Der Link wird nun richtig ersetzt bei mir.

Vielen Dank!

**Comment by zoglo** [comment]
Fixed with Version 2.0.5
https://github.com/oveleon/contao-glossary-bundle/releases/tag/2.0.5
