### ISSUE TITLE
502 Bad Gateway bei mehr als 100 Einträgen

### ISSUE THREAD

**Issue by m-r-h-n** [oveleon/contao-glossary-bundle#16]
Hallo,
vorab dickes Lob - tolle Erweiterung!
Ich habe gerade testweise Update von der Version 1.0.3 auf die aktuelle 2.0.6 gemacht und lief danach in einen 502 Fehler.
Anscheinend passiert das nur, wenn mehr als 103 Einträge (jedenfalls in meiner Umgebung) in der Übersicht aktiv sind.
Wenn ich die Paginierung aktiviere taucht der Fehler nicht auf.
In der älteren 1er Version lief es ohne Probleme.
PHP 7.4 FPM
memory_limit 512M

**Comment by eki89** [comment]
Hallo m-r-h-n,
ich kann den Fehler anhand deiner Angaben leider nur schwer zuordnen. 502-Fehler hört sich erstmal danach an, als hätte es nichts direkt mit der Erweiterung zu tun. Wird zufällig ein Fehler im Systemlog aufgeführt, wenn du den Fehler provozierst?

**Comment by m-r-h-n** [comment]
Hallo Fabian,

danke für die fixe Rückmeldung.
Habe gerade noch mal den DEV Modus abgeklemmt und da passiert der Fehler nicht.
Ist also nur ein Fehler sobald der DEV Modus an ist.

Anbei noch mal Logs im DEV Modus:

Server Log:
[fcgid:warn] [pid 2134] (32)Broken pipe: [client MEINE IP] mod_fcgid: ap_pass_brigade failed in handle_request_ipc function, referer:

Proxy Log:
2022/03/02 14:44:08 [error] 9782#0: *13024473 upstream sent too big header while reading response header from upstream, client: MEINE IP, server: MEIN SERVER, request: "GET /service/glossar.html HTTP/2.0“

Contao Dev Log:
[2022-03-02T13:49:07.004903+00:00] request.INFO: Matched route "tl_page.28". {"route":"tl_page.28","route_parameters":{"_token_check":true,"_controller":"Contao\\FrontendIndex::renderPage","_scope":"frontend","_locale":"de","_format":"html","_canonical_route":"tl_page.28","parameters":"","pageModel":{"Contao\\PageModel":[]},"_route":"tl_page.28","_route_object":{"Contao\\CoreBundle\\Routing\\Page\\PageRoute":[]}},"request_uri“:“MEINE WEBSITE/service/glossar.html","method":"GET"} []
[2022-03-02T13:49:07.038158+00:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2022-03-02T13:49:07.039039+00:00] app.DEBUG: Router Symfony\Bundle\FrameworkBundle\Routing\Router was not able to match, message "No routes found for "/service/glossar.html/"." [] []


Grüsse,
Andre (m-r-h-n)



> Am 02.03.2022 um 14:40 schrieb Fabian Ekert ***@***.***>:
> 
> 
> Hallo m-r-h-n,
> ich kann den Fehler anhand deiner Angaben leider nur schwer zuordnen. 502-Fehler hört sich erstmal danach an, als hätte es nichts direkt mit der Erweiterung zu tun. Wird zufällig ein Fehler im Systemlog aufgeführt, wenn du den Fehler provozierst?
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> You are receiving this because you authored the thread.
> 

Dipl. Kommunikationsdesigner

------------------
|  MAROHN  |
------------------
Kommunikation und Design
Albert-Schweitzer-Str. 4
25746 Heide
---
fon: 0481 - 78768710
mail: ***@***.***
web: www.mrhn.de
--
St. Nr. 1601424981
USt. Id.: DE 269125999

**Comment by eki89** [comment]
Ich würde anhand deiner Angaben das Problem bei der Serverkonfiguration verorten. Bei Google findest du sehr viele Informationen zu Problemen die sehr ähnlicher Natur sind. Google einfach mal "ap_pass_brigade". Irgendwo hast du einen Flaschenhals der durch den 103ten Glossareintrag ausgeschöpft zu sein scheint. Der Fehler wird aber vermutlich nicht direkt mit unserer Erweiterung in Zusammenhang stehen.

Der Fehler taucht vermutlich deswegen momentan nur im Debugmodus auf, da die Seite im Debugmodus mehr Serverressourcen benötigt. Ggf. könnte das Problem also mit der Zeit akuter werden. Dies ist aber nur eine vermutung meinerseits, sodass ich hier keine verbindliche Aussage treffen kann.

**Comment by m-r-h-n** [comment]
Hi,

yo danke :-)
Denke auch es liegt am Server.
Hatte die 1er Version auch nur lange im Dev Modus laufen und da trat der Fehler nicht auf. Deswegen war ich erstmal leicht irritiert.


Grüsse,
Andre

> Am 02.03.2022 um 15:13 schrieb Fabian Ekert ***@***.***>:
> 
> 
> Ich würde anhand deiner Angaben das Problem bei der Serverkonfiguration verorten. Bei Google findest du sehr viele Informationen zu Problemen die sehr ähnlicher Natur sind. Google einfach mal "ap_pass_brigade". Irgendwo hast du einen Flaschenhals der durch den 103ten Glossareintrag ausgeschöpft zu sein scheint. Der Fehler wird aber vermutlich nicht direkt mit unserer Erweiterung in Zusammenhang stehen.
> 
> Der Fehler taucht vermutlich deswegen momentan nur im Debugmodus auf, da die Seite im Debugmodus mehr Serverressourcen benötigt. Ggf. könnte das Problem also mit der Zeit akuter werden. Dies ist aber nur eine vermutung meinerseits, sodass ich hier keine verbindliche Aussage treffen kann.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> You are receiving this because you authored the thread.
> 

Dipl. Kommunikationsdesigner

------------------
|  MAROHN  |
------------------
Kommunikation und Design
Albert-Schweitzer-Str. 4
25746 Heide
---
fon: 0481 - 78768710
mail: ***@***.***
web: www.mrhn.de
--
St. Nr. 1601424981
USt. Id.: DE 269125999

**Comment by eki89** [comment]
Alles klar, kein Problem. Ich wünsche dir viel Erfolg bei der Fehlersuche. Wenn du einen Fehler in unserer Erweiterung findest kannst du dich gerne wieder an uns wenden.
