### ISSUE TITLE
Fehlermeldung beim Anlegen eines neuen Eintrags in ein Glossar. Bug?

### ISSUE THREAD

**Issue by omuellersch** [oveleon/contao-glossary-bundle#17]
Beim Erstellen/anlegen eines neuen Eintrags in ein Glossar erscheint eine Contao-Fehlermeldung:

"An exception occurred while executing 'INSERT INTO tl_glossary_item (`pid`, `tstamp`) VALUES ('1', 0)': SQLSTATE[HY000]: General error: 1364 Field 'glossary_faq_answer' doesn't have a default value"

Kopieren/Einfügen eines Eintrags funktioniert.

Contao 4.9.26
Contao Glossar Bundle 2.0.6

**Comment by zoglo** [comment]
Hello @omuellersch ,

the field "glossary_faq_answer" is not a field from our glossary bundle.
Make sure to check whether you added a custom field into any of the existing DCAs or if you have any other plugin installed that uses this.
