### ISSUE TITLE
Multiple Languages

### ISSUE THREAD

**Issue by operatorone** [oveleon/contao-glossary-bundle#18]
Hi there, 

do you have any plans to make the glossary able to handle multiple languages? I'm working on a website which uses German and English and change_language as language extension. Currently I have two archives, one for every language. 

Or do you have an idea how to redirect the visitor to the overview page, if he wants to switch the language on the detail page of the glossary?

I'm looking forward to your response.

**Comment by zoglo** [comment]
Hello @operatorone ,

we did not plan to implement multi-language support as of now.

What you could do is the following:
- copy your glossary (the archive) with all your items and edit the glossary entries to be in english language
- Create a new glossary list and reader with the new archive, additionally you could set up your English page root to include the hover cards
- embed the new modules within your english pages

As for redirecting from the detail page to the overview page, I'd suggest setting up the reader page within the change_language settings to redirect to the glossary archive. This would only work oneway though.

**Comment by operatorone** [comment]
Thanks for your reply. I did as you described and it works fine. 

May be in the future there will be the opportunity to create multiple archives, define one as fallback and then refer to a fallback entry within the foreign language entry. This may be a wonderful feature for this exquisite extension.
