### ISSUE TITLE
notwendige Rechte für Benutzergruppe

### ISSUE THREAD

**Issue by rustykowski** [oveleon/contao-glossary-bundle#21]
Mir gelingt es nicht, Redakteuren Zugriff auf das Glossar zu geben.
Konstellation: Contao 4.13., Glossary-Bundle 2.0.7, PHP 8.1.

Meine Benutzergruppen-Konfiguration:
Backendmodule: Nur Glossare
Inhaltselemente: Text, Bild etc.
Glossar-Rechte: Das gewünschte Glossar ist aktiviert
Erlaubte Felder: die meisten in tl_content, alle in tl_glossary_item

Der Redakteur kann das Glossar öffnen, alle Begriffe sehen, aber sobald er einen neuen Begriff anlegen oder einen bestehenden bearbeiten möchte, erhält er die Fehlermeldung Forbidden: "Not enough permissions to edit glossary item ID x of glossary ID y." bzw. "Not enough permissions to modify article ID x in glossary ID y."

Habe ich eine Berechtigung vergessen?

**Comment by zoglo** [comment]
@rustykowski should be fixed. Can you install the new version (2.0.8) and check it fit works?

**Comment by rustykowski** [comment]
Thanks for the quick bugfix! Permissions are working perfectly now.
