### ISSUE TITLE
Use <abbr>

### ISSUE THREAD

**Issue by Fanni-Portier** [oveleon/contao-glossary-bundle#24]
I have activated a glossary of abbreviations in the website root.

Can I change the frontend output to use an <abbr> tag with a <title> tag?
I don't need a link - just an accessible abbreviations solution.

**Comment by zoglo** [comment]
Hey @Fanni-Portier ,

creating markups is possible via 'markup' in your config_glossary_default
https://github.com/oveleon/contao-glossary-bundle#settings-2

However, the teaser descriptions are parsed asynchronously.

This could be a feature that we could implement but if you need it right now, there is an existing API in the glossary bundle that allows you to use it with the jquery plugin [Glossarizer](https://github.com/PebbleRoad/glossarizer).

You could deactivate the glossary within your page settings and use following API-route:
```/api/glossary/glossarizer```

This would  work for the mentioned plugin above as the "sourceURL" as seen in their [Documentation](https://github.com/PebbleRoad/glossarizer#2-initialize-the-plugin)

**Comment by Fanni-Portier** [comment]
Thanks very much!

I tried to construct the <abbr> tag with "markup" but that didn't work.
I'll try my luck with Glossarizer.

**Comment by zoglo** [comment]
Yeah, it's currently not supported and should only work with the hovercard. It's a good feature request tho so no promises when it'll be done but it could be implemented in a next version.

**Comment by Fanni-Portier** [comment]
Great!
If you do - please add a lang attribute option.

**Comment by zoglo** [comment]
@Fanni-Portier 

could you install the current *dev-develop* branch and test the new "abbr"-feature?

Just use this as your **config_glossary_default.html5**
```
<?php
  $GLOBALS['TL_JAVASCRIPT'][] = 'bundles/contaoglossary/scripts/dist/main.js|static';
  $GLOBALS['TL_CSS'][] =        'bundles/contaoglossary/styles/glossary.css';
?>

<script>
  const GN = new Glossary({
    'markup': 'abbr',
    'hovercard': {
        'active': <?= $this->hoverCardMode ?: 0 ?>
    },
    'route': {
      'cache': <?= $this->cacheStatus ?: 0 ?>
    },
    'config': <?= $this->glossaryConfig ?: 'null' ?>
  });
</script>
```

I coded it so using abbr will deactivate hovercards for now.
I would need to write a migration and will most likely change the option within tl_page to something similar like "show description" with options like ('within hovercard', 'within abbr').

Can you check it out within **debug mode** and outside of it as well? (Added session storage caching)

I'll check the lang attribute next

**Comment by zoglo** [comment]
There still seems to be a bug where the newly added description will be parsed as well if it holds any keywords.

**Comment by zoglo** [comment]
@Fanni-Portier Sorry it took so long, had to think of a solution.
Could you test the current dev-branch? (dev-development).

The new change https://github.com/oveleon/contao-glossary-bundle/commit/bfa812ebb18faa374477e82b98c751c1bbf1652a also improved not always changing the node-content if nothing has been found.

**Comment by zoglo** [comment]
Fixed with https://github.com/oveleon/contao-glossary-bundle/releases/tag/2.1.0
