### ISSUE TITLE
SitemapListener issue

### ISSUE THREAD

**Issue by FilipSec** [oveleon/contao-glossary-bundle#33]
While using your extension for my glossary, i had an issue with sitemap entries. Namely, the SitemapListener that you provide lists all entries by it's aliases, and that's the way it should be when you have detailed glossary. However, on my site i have only glossary list with jumping points when clicked on letters, and thus my sitemap got unnecessarily clogged with entries for each alias. So i wrote an event listener that would override your functionality and added it to services.yaml, and noticed that nothing changed. Then i ran `php bin/console debug:event-dispatcher` on my server and it showed that the SitemapListener gets invoked multiple times( log from that in text document). Analyzing further, i saw that you have the service defined both via annotation in SitemapListener.php and services.yaml file which leads to it being registered twice and thus I wasn't able to override it. When i removed annotation it invokes only once in event dispatcher and gets overwritten with my custom Listener without issues. I've tried the same approach with GeneratePageListener and had no issues overriding, since that one is registered only in listener.yaml
![annotation](https://github.com/oveleon/contao-glossary-bundle/assets/36379552/a3494375-6dcc-4d45-b6a4-000cc84977d1)
[event dispatcher.txt](https://github.com/oveleon/contao-glossary-bundle/files/13602221/event.dispatcher.txt)

**Comment by zoglo** [comment]
@FilipSec can you test the dev-develop branch?

I also added a new template: glossary_teaaser.html5 that does not show the addmore + linkHeadline as jumpTo is not mandatory anymore.

**Comment by FilipSec** [comment]
@zoglo Thank you for the quick response and fix, i will test it out later today from develop branch and get back to you with the feedback

**Comment by FilipSec** [comment]
I'm having some troubles with SSH tunnel today, so i will need to verify the invoking of the services tomorrow. After setting the extension to dev-develop, resetting the cache and purging XML, once again it generates the terms for every single alias in glossary( therefore it isn't overridden by my service and listener). I'll get back to you tomorrow when i check it more thoroughly though.

**Comment by zoglo** [comment]
> I'm having some troubles with SSH tunnel today, so i will need to verify the invoking of the services tomorrow. After setting the extension to dev-develop, resetting the cache and purging XML, once again it generates the terms for every single alias in glossary( therefore it isn't overridden by my service and listener). I'll get back to you tomorrow when i check it more thoroughly though.

I've tested the invoking of the services myself and it was indeed happening twice.
Just the annotation is enough to invoke it so I removed it.

It is/was a bug but for your use-case, I've made sure that you don't have to setup a redirect-page in the glossary which makes sure your pages are never shown in the sitemap :).

**Comment by FilipSec** [comment]
Yes, I understood that leaving only annotation solves the issue of it being invoked twice. However, if it's invoked via annotation, me( or anyone else) cannot overwrite it with our custom logic for Sitemap. When it is only invoked in services.yaml, without annotation in the SitemapListener( this is what i tested before opening the issue), it invokes once and user can overwrite the logic by creating his own Sitemap logic in EventListener or just unsetting it completely in services.yaml(which was my case, since i need no entries to sitemap from glossary, just the glossary page which is already handled by Contao). So i think that one solution would be to leave it defined in services.yaml and remove the annotation. As for additional changes, yes, that works also when i remove redirect, but i think it might be a good idea to have both options in case someone needs a redirect page and a different sitemap logic than yours, that way your service would be easily overridable and customisable without losing anything( if i'm not missing something obvious)

**Comment by FilipSec** [comment]
I wasn't aware of this, thanks. I guess you can then close the issue as solved, since the double invoke doesn't happen anymore(with either approach) and with jumpTo no longer being mandatory it will work without overwrites(works as intended in my use case). :)

**Comment by zoglo** [comment]
Fixed in https://github.com/oveleon/contao-glossary-bundle/releases/tag/2.2.2
