### ISSUE TITLE
Einstellung für Robots-Tag wird nicht übernommen

### ISSUE THREAD

**Issue by webmarketiere** [oveleon/contao-glossary-bundle#38]
Einstellung für Robots-Tag wird nicht übernommen.

Contao 4.13.39
Contao Glossar Bundle 2.2.3

**Comment by zoglo** [comment]
@webmarketiere Would you be able to describe your issue a lil bit better?

**Comment by webmarketiere** [comment]
In the page settings for the reader module, is "index,follow" set by default in the robots tag. If I want to overwrite the setting directly in the entry with "noindex,follow", this setting does not take effect.

**Comment by zoglo** [comment]
Fixed in 2.2.4
