### ISSUE TITLE
Error on save for edit/new entries | "Using $this when not in object context"

### ISSUE THREAD

**Issue by Paddy0174** [oveleon/contao-glossary-bundle#48]
I get this error message when I try to save a newly added glossary item or an already there entry, so basically saving a glossary entry (not the ce) isn't possible.

"Internal Server Error" and "Using $this when not in object context"

I suspect the new version 2.3.0, installed yesterday.

What can I do to make debugging this easier? What logs do you need? For now there is _no_ entry in any logs (neither apache2 nor nginx)

Contao version: 5.3.15
Glossary bundle: 2.3.0
Hosting: Hostingwerk

Reproducing steps in my installation:
Got to glossary, select a glossary and add a new entry. Fill in anything, just a name for the entry will do and click "save" or "save & close" and the next screen is the above mentioned error message. Going back doesn't show anything added. 

Thanks for any ideas!

**Comment by zoglo** [comment]
See https://github.com/oveleon/contao-glossary-bundle/releases/tag/2.3.1

**Comment by Paddy0174** [comment]
Thanks a lot! What a lightning speed for a fix! Wow! (<= me, being very impressed!)

Oh and yes, everything is working as expected! Thank you very much! :)
