### ISSUE TITLE
Template selection in list module does not work

### ISSUE THREAD

**Issue by dive13** [oveleon/contao-glossary-bundle#49]
The selection of templates (glossary_full, glossary_short etc.) in the Glossary module has no effect on the display in the frontend.
The list display can therefore not be customized.

Contao 4.13.49
Contao Glossary Bundle 2.3.1

**Comment by zoglo** [comment]
See: https://github.com/oveleon/contao-glossary-bundle/releases/tag/2.3.2

**Comment by dive13** [comment]
Thank you very much for the exceptionally quick fix!
