### ISSUE TITLE
Berechtigungen für nicht-Admin

### ISSUE THREAD

**Issue by arboc** [oveleon/contao-glossary-bundle#51]
Wir haben die Berechtigungen wie folgt gesetzt:
1. Backend-Module -> Inhalte -> Glossare (check)
![image](https://github.com/user-attachments/assets/9d653dc2-c3fb-48e6-9cb7-57f1d3af2989)
2. Glossar-Rechte:
![image](https://github.com/user-attachments/assets/b4a91b84-dbae-4606-8a8c-ea6e67e5f2cc)
3. Erlaubte Felder: glossary und glossary_item: komplett
![image](https://github.com/user-attachments/assets/6656303e-1a4f-4f63-b40c-955c35a01e43)

Dennoch kann der Benutzer (kein Admin, mit o.g. Rechten) keine Einträge bearbeiten oder anlegen. Es kommt der Hinweis:
![image](https://github.com/user-attachments/assets/0c22f868-ae42-449a-983c-ad0762371670)

Wir arbeiten mit
PHP 8.3
Contao 4.13.49
Glossar-Bundle 2.3.2

**Comment by zoglo** [comment]
Did you try `glossaryp` aka `glossary permissions` ?

**Comment by arboc** [comment]
yes, I also tried the glossaryp permissions. Same behaviour.  
But the user should not be allowed to add new glossaries. But the user should be able to add glossary items. But that is not possible.

I saw 2 issues:
1. strict use of types with in_array, where one type is string and the other is integer.
2. use $user->publicatios, which is not defined.

hope that helps.

**Comment by zoglo** [comment]
Feel free to create a PR if you already know how to properly fix it 😊

**Comment by zoglo** [comment]
I've changed `2.` - please test the current dev-main
