### ISSUE TITLE
Compatibility hschottm/tags

### ISSUE THREAD

**Issue by siegelsupport** [oveleon/contao-glossary-bundle#54]
Hi,

Thank you for the great extension.
Would it be possible to make it compatible with the tags extension at the level of the settings of a glossary entry?
That would be great.

Thank you and best regards

Robert

**Comment by zoglo** [comment]
Hey @siegelsupport, I never used the tags extension but it looks like it would create an unnecessary dependency if I'd have to add tag-support for the glossary bundle. People would either have to install the tags extension or I'd have to code around it so the specific fields do not get added.

It would be easier if you'd simply do it within your specific system as described here:
https://github.com/hschottm/tags?tab=readme-ov-file#adding-tag-support-for-contao-data-containers

You'd be able to create a `contao/dca` folder within the root of your application/website and handle this yourself.

More information about extending Datacontainers can be found within the contao docs:
https://docs.contao.org/manual/de/anleitungen/dca/

**Comment by siegelsupport** [comment]
@zoglo Thank you very much for the quick reply, that's what I'll do ;-)
