### ISSUE TITLE
Keine Glossar-Einträge, wenn man als FrontendUser angemeldet ist

### ISSUE THREAD

**Issue by arboc** [oveleon/contao-glossary-bundle#55]
Wenn man als Frontenduser angemeldet ist, werden keine Glossar-Einträge in der Liste angezeigt.    
Unabh. ob das Glossar oder das Modul geschützt ist.

Im GlossaryTrait Zeile 456 ff findet sich folgender Code:

```php
        if ($user instanceof FrontendUser)
        {
            return [];
        }
```

Ich habe keine Ahnung, warum dieses Fragment existiert, und warum ein leeres Array zurückgegeben werden sollte.   
Jedenfalls ist dies der Grund, warum keine Einträge gelistet werden.

Wenn ich den Schnipsel lösche, funktioniert alles. Ich kann eine Pull-Request machen, aber ich denke, es gab einen Grund, warum dies so programmiert wurde. Mir ist nur nicht klar welcher.

**Comment by zoglo** [comment]
Nope, ist ein Bug und war beim Umschreiben dazu gekommen (noch ist das alles nicht perfekt.. man sollte eher DI nutzen als sich immer den Container zu holen aber irgendwann :) )

See 1e21cb5ad43d5b6937aff6d9c2a76ddb1d52c97d

See: https://github.com/oveleon/contao-glossary-bundle/releases/tag/2.3.4

**Comment by arboc** [comment]
Danke für das schnelle fixen.
