### ISSUE TITLE
Glossar nur auf bestimmten Seiten verfügbar machen

### ISSUE THREAD

**Issue by freiwild** [oveleon/contao-glossary-bundle#6]
Eine weitere Verbesserung wäre, die Glossareinträge nur auf bestimmten Seiten verfügbar zu machen. Denn es ist nicht passend, wenn Stichwörter auf der gesamten Site gesucht und Links gesetzt werden, wie z. B. in Teasern für News/Events, o. ä. 
Aktuell kann die Verlinkung der Stichwörter nur für die gesamte Website aktiviert werden. Optimaler wäre, wenn die Stichwörter nur für einzelne Seiten verfügbar gemacht werden könnten oder alternativ für einzelne Seiten deaktiviert werden könnten.

**Comment by zoglo** [comment]
Hallo @freiwild ,

siehe Dokumentation: https://github.com/oveleon/contao-glossary-bundle#regular-page-settings

> oder alternativ für einzelne Seiten deaktiviert werden könnten.

Auf regulären Seiten gibt es unter den Experten-Einstellungen eine Option "Glossar deaktivieren".

**Comment by freiwild** [comment]
Ups! :) Stark, an alles gedacht! :) Danke!
