### ISSUE TITLE
Bug in Glossar-Item veröffentlichen/unveröffentlichen

### ISSUE THREAD

**Issue by freiwild** [oveleon/contao-glossary-bundle#7]
Die Funktion, mit der ein  Glossar-Item veröffentlichen/unveröffentlichen kann, scheint fehlerhaft. 
Mit Hilfe des "Auge"-Symbols sowohl in der Übersichtsliste der Glossary-Items als auch in der Kopfzeile in der Item-Detailansicht kann das Item nicht veröffentlicht werden. Zwar ändert das "Auge" die Farbe zu grün, es bleibt aber unsichtbar und nach einem Reload der Seite ist das Symbol wieder grau. Das Ausblenden hingegen funktioniert über die Augen-Symbole.

In den Item-Einstellungen unter "Veröffentlichen", funktioniert veröffentlichen und unveröffentlichen.

Contao v4.9.22, Contao Glossar Bundle v2.0.1, PHP 7.4

**Comment by zoglo** [comment]
Hello @freiwild ,

thanks for reporting that issue. It should be fixed with the newest release!

https://github.com/oveleon/contao-glossary-bundle/releases/tag/2.0.2
